"""
Models Package - Database models for the Play Buni Platform.

This module imports all database models to ensure they are registered
with SQLAlchemy for proper table creation and relationship handling.
"""

# Import all models to register them with SQLAlchemy
from .users import (
    User,
    NFTHolder,
    UserSession,
    SignalInteraction,
    # Pydantic schemas
    UserBase,
    UserCreate,
    UserUpdate,
    UserResponse,
    NFTHolderBase,
    NFTHolderCreate,
    NFTHolderUpdate,
    NFTHolderResponse,
    UserSessionBase,
    UserSessionCreate,
    UserSessionResponse,
    SignalInteractionBase,
    SignalInteractionCreate,
    SignalInteractionResponse,
    UserStats,
    NFTVerificationResult,
    UserActivity,
)

from .signals import (
    Signal,
    SignalPerformance,
    SignalQueue,
    # Enums
    SignalType,
    SignalStrength,
    SignalStatus,
    DistributionChannel,
    # Pydantic schemas
    SignalBase,
    SignalCreate,
    SignalUpdate,
    SignalResponse,
    SignalPerformanceBase,
    SignalPerformanceCreate,
    SignalPerformanceUpdate,
    SignalPerformanceResponse,
    SignalQueueBase,
    SignalQueueCreate,
    SignalQueueUpdate,
    SignalQueueResponse,
    SignalStats,
    SignalAnalytics,
    TrendingToken,
)

from .blinks import (
    Blink,
    Trade,
    Revenue,
    # Enums
    BlinkType,
    BlinkStatus,
    TradeStatus,
    TradeType,
    # Pydantic schemas
    BlinkBase,
    BlinkCreate,
    BlinkUpdate,
    BlinkResponse,
    TradeBase,
    TradeCreate,
    TradeUpdate,
    TradeResponse,
    RevenueBase,
    RevenueCreate,
    RevenueUpdate,
    RevenueResponse,
    BlinkStats,
    TradeStats,
    RevenueStats,
    JupiterQuoteRequest,
    JupiterSwapRequest,
)

from .analytics import (
    PlatformAnalytics,
    SocialPost,
    UserFeedback,
    SystemEvent,
    # Enums
    AnalyticsType,
    SocialPlatform,
    PostStatus,
    FeedbackType,
    # Pydantic schemas
    PlatformAnalyticsBase,
    PlatformAnalyticsCreate,
    PlatformAnalyticsResponse,
    SocialPostBase,
    SocialPostCreate,
    SocialPostUpdate,
    SocialPostResponse,
    UserFeedbackBase,
    UserFeedbackCreate,
    UserFeedbackUpdate,
    UserFeedbackResponse,
    SystemEventBase,
    SystemEventCreate,
    SystemEventResponse,
    AnalyticsSummary,
    SocialEngagement,
    FeedbackSummary,
    UserEngagementMetrics,
)

# Export all models for easy importing
__all__ = [
    # SQLAlchemy Models
    "User",
    "NFTHolder", 
    "UserSession",
    "SignalInteraction",
    "Signal",
    "SignalPerformance",
    "SignalQueue",
    "Blink",
    "Trade",
    "Revenue",
    "PlatformAnalytics",
    "SocialPost",
    "UserFeedback",
    "SystemEvent",
    
    # Enums
    "SignalType",
    "SignalStrength",
    "SignalStatus",
    "DistributionChannel",
    "BlinkType",
    "BlinkStatus",
    "TradeStatus",
    "TradeType",
    "AnalyticsType",
    "SocialPlatform",
    "PostStatus",
    "FeedbackType",
    
    # User Schemas
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "NFTHolderBase",
    "NFTHolderCreate",
    "NFTHolderUpdate",
    "NFTHolderResponse",
    "UserSessionBase",
    "UserSessionCreate",
    "UserSessionResponse",
    "SignalInteractionBase",
    "SignalInteractionCreate",
    "SignalInteractionResponse",
    "UserStats",
    "NFTVerificationResult",
    "UserActivity",
    
    # Signal Schemas
    "SignalBase",
    "SignalCreate",
    "SignalUpdate",
    "SignalResponse",
    "SignalPerformanceBase",
    "SignalPerformanceCreate",
    "SignalPerformanceUpdate",
    "SignalPerformanceResponse",
    "SignalQueueBase",
    "SignalQueueCreate",
    "SignalQueueUpdate",
    "SignalQueueResponse",
    "SignalStats",
    "SignalAnalytics",
    "TrendingToken",
    
    # Blink & Trading Schemas
    "BlinkBase",
    "BlinkCreate",
    "BlinkUpdate",
    "BlinkResponse",
    "TradeBase",
    "TradeCreate",
    "TradeUpdate",
    "TradeResponse",
    "RevenueBase",
    "RevenueCreate",
    "RevenueUpdate",
    "RevenueResponse",
    "BlinkStats",
    "TradeStats",
    "RevenueStats",
    "JupiterQuoteRequest",
    "JupiterSwapRequest",
    
    # Analytics & Social Schemas
    "PlatformAnalyticsBase",
    "PlatformAnalyticsCreate",
    "PlatformAnalyticsResponse",
    "SocialPostBase",
    "SocialPostCreate",
    "SocialPostUpdate",
    "SocialPostResponse",
    "UserFeedbackBase",
    "UserFeedbackCreate",
    "UserFeedbackUpdate",
    "UserFeedbackResponse",
    "SystemEventBase",
    "SystemEventCreate",
    "SystemEventResponse",
    "AnalyticsSummary",
    "SocialEngagement",
    "FeedbackSummary",
    "UserEngagementMetrics",
] 